/*=============================================================================
                                   LibPlot2D
                       Copyright Kerry R. Loux 2011-2016

                  This code is licensed under the GPLv2 License
                    (http://opensource.org/licenses/GPL-2.0).
=============================================================================*/

// File:  baumullerFile.h
// Date:  10/4/2012
// Auth:  K. Loux
// Desc:  File class for Baumuller files.

#ifndef BAUMULLER_FILE_H_
#define BAUMULLER_FILE_H_

// Local headers
#include "lp2d/parser/dataFile.h"

namespace LibPlot2D
{

/// Class representing Baumuller plot files generated by WinBassII or ProDrive
/// software.
class BaumullerFile final : public DataFile
{
public:
	/// Constructor.
	///
	/// \param fileName Path and file name of desired file.
	explicit BaumullerFile(const wxString& fileName) : DataFile(fileName) {}

	~BaumullerFile() = default;

	/// Checks to determine if the specified file can successfully be an object
	/// of this type.
	///
	/// \param fileName Path and file name of desired file.
	///
	/// \returns True if the specified file is likely to be compatible with an
	/// object of this type.
	static bool IsType(const wxString &fileName);

protected:
	wxArrayString GetCurveInformation(unsigned int &headerLineCount,
		std::vector<double> &factors,
		wxArrayInt &nonNumericColumns) const override;
	void DoTypeSpecificLoadTasks() override;
	void DoTypeSpecificProcessTasks() override;

private:
	bool ConstructNames(std::string &nextLine, std::ifstream &file,
		wxArrayString &names, wxArrayString &previousLines) const;

	friend std::unique_ptr<DataFile>
		DataFile::Create<BaumullerFile>(const wxString&);
};

}// namespace LibPlot2D

#endif//BAUMULLER_FILE_H_
